// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalFYP.Models;

public partial class Admin
{
    public int AdminId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }
}