// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalFYP.Models;

public partial class Billing
{
    public int BillingId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? PhoneNumber { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string PostCode { get; set; }

    public string Country { get; set; }

    public string State { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}