// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalFYP.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public string CustomerName { get; set; }

    public string Icnumber { get; set; }

    public string CustomerPhoneNumber { get; set; }

    public string PickUpLocation { get; set; }

    public DateTime? PickUpDate { get; set; }

    public TimeSpan? PickUpTime { get; set; }

    public string DropOffLocation { get; set; }

    public DateTime? DropOffDate { get; set; }

    public TimeSpan? DropOffTime { get; set; }

    public string BabySeat { get; set; }

    public string UsbCable { get; set; }

    public string PhoneHolder { get; set; }

    public int? VehicleId { get; set; }

    public int? PaymentId { get; set; }

    public int? BookingStatusId { get; set; }

    public int? LocationId { get; set; }

    public int? CarId { get; set; }

    public int? Amount { get; set; }

    public string Email { get; set; }

    public string PaymentType { get; set; }

    public string OrderId { get; set; }

    public virtual BookingStatus BookingStatus { get; set; }

    public virtual Car Car { get; set; }

    public virtual Location Location { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}