// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalFYP.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string Name { get; set; }

    public string PlateNumber { get; set; }

    public int? Year { get; set; }

    public string Color { get; set; }

    public string Notes { get; set; }

    public int? CarStatusId { get; set; }

    public int? VehicleId { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual CarStatus CarStatus { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}