// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalFYP.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public DateTime? Date { get; set; }

    public string CallBackStatus { get; set; }

    public string ReferenceNumber { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}