// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarRentalFYP.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public string Name { get; set; }

    public byte[] Image { get; set; }

    public int? Price { get; set; }

    public int? NumberOfSeat { get; set; }

    public int? Deposit { get; set; }

    public int? EngineCapacity { get; set; }

    public int? Year { get; set; }

    public int? VehicleCategoryId { get; set; }

    public int? VehicleTransmissionId { get; set; }

    public int? VehicleFuelId { get; set; }

    public string ImageTwo { get; set; }

    public string ImageThree { get; set; }

    public string ImageFour { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Car> Cars { get; set; } = new List<Car>();

    public virtual VehicleCategory VehicleCategory { get; set; }

    public virtual VehicleFuel VehicleFuel { get; set; }

    public virtual VehicleTransmission VehicleTransmission { get; set; }
}